// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVg0UCtXqBIk-joikkcabo6mfm9XZwugQ',
    appId: '1:152026182721:web:132245406df42f486f02c0',
    messagingSenderId: '152026182721',
    projectId: 'tailor-book-5b877',
    authDomain: 'tailor-book-5b877.firebaseapp.com',
    storageBucket: 'tailor-book-5b877.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoymH9ks_ClP8lmAh0g6XENjVNtGf4oMU',
    appId: '1:152026182721:android:47123e59884e23076f02c0',
    messagingSenderId: '152026182721',
    projectId: 'tailor-book-5b877',
    storageBucket: 'tailor-book-5b877.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR6fJVKwMF5qyt00uz9jG4OQr5TYdnrI8',
    appId: '1:152026182721:ios:bf4c20a5b62b6ecf6f02c0',
    messagingSenderId: '152026182721',
    projectId: 'tailor-book-5b877',
    storageBucket: 'tailor-book-5b877.appspot.com',
    iosClientId: '152026182721-3ufll60og4gtl3popl0rdbsc0bchka9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailorBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR6fJVKwMF5qyt00uz9jG4OQr5TYdnrI8',
    appId: '1:152026182721:ios:bf4c20a5b62b6ecf6f02c0',
    messagingSenderId: '152026182721',
    projectId: 'tailor-book-5b877',
    storageBucket: 'tailor-book-5b877.appspot.com',
    iosClientId: '152026182721-3ufll60og4gtl3popl0rdbsc0bchka9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailorBook',
  );
}
